Foundryborne/daggerheart

module/applications/sheets/pc.mjs

Update PC forms to be resizeable

Allow PC Forms to be resizeable

---

module/applications/sheets/character.mjs
module/config/flagsConfig.mjs
module/config/system.mjs
module/data/actor/character.mjs
styles/daggerheart.css
styles/less/actors/character/loadout.less
templates/sheets/actors/character/loadout.hbs
templates/sheets/global/partials/domain-card-item.hbs
templates/sheets/global/partials/inventory-fieldset-items.hbs

Add ability to toggle between list and card views

---

module/applications/sheets/character.mjs

- change propriety from `actor.system.resources.hitPoints.max` to `actor.system.resources.hitPoints.maxTotal`

[Bugfix] Fix death roll function

---

styles/characterCreation.less

- Fix char setup scroll adding overflow-y on tabs
- closes #202

[Bugfix] Fix char setup dialog overflow

---

pull_request_template.md

- Fixes mistake in pull request template
n/a
n/a
---

fixed pull request template

---

styles/daggerheart.css
styles/less/global/elements.less
templates/sheets/global/partials/inventory-item.hbs

* Inventory items now have descriptions
* CSS resolved to improve visuals for the description above (Rich text issue is still unresolved)
- Fixes #(issue): [Feature] Collapsible Items Description in List View #198
- Closes #(issue): none
Please describe the tests you ran to verify your changes: 
1. Launched Server
2. Open Character Sheet
3. View Inventory Tab
Made changes but Rich Text is still broken. Will be resolved later.
---

[Feature] Collapsible Items Description in List View #198

---

lang/en.json
module/applications/sheets/actors/environment.mjs
module/applications/sheets/applications/environment-settings.mjs
templates/sheets/global/partials/inventory-item.hbs

Fixed so edit/view/delete of potential adversary is handled if the adversary Actor has been removed from the world

[Bug] Potential Adversary When Removed

---

module/applications/roll.mjs
module/data/action/action.mjs

- Issue: https://github.com/Foundryborne/daggerheart/issues/236

Feature/236 - Critical Damage formula

---

module/applications/sheets/actors/character.mjs

REFACTOR: move _createSearchFilter from `_onFirstRender` to `_onRender`

---

module/applications/sheets/actors/adversary.mjs
module/data/actor/adversary.mjs
templates/sheets-settings/adversary-settings/experiences.hbs
templates/sheets/actors/adversary/sidebar.hbs

Changed experience schema field name from 'modifier' to 'total' to match useage in Character and Companion
- Closes #286

286 - Adversary Experience Value Bug

---

module/applications/dialogs/d20RollDialog.mjs

Fix Roll Dialog Button check

---

module/data/chat-message/dualityRoll.mjs
module/dice/d20Roll.mjs
module/dice/dhRoll.mjs
module/dice/dualityRoll.mjs
module/helpers/utils.mjs

Fixed DiceSoNice integration again.
- The colour setting method had misstakenly gone away during some rework.
- Some fields had fallen away from DualityDice data model, causing an error during chatMessage rerender.

[BUG] DiceSoNice fix  

---

module/data/action/baseAction.mjs

Fix to make Cosmo happy

---

module/data/actor/companion.mjs

Fixed so companion damage uses partner proficiency for scaling

Companion Damage Scaling

---

module/applications/sheets/actors/adversary.mjs
module/applications/sheets/actors/character.mjs
module/applications/sheets/actors/environment.mjs
styles/less/global/elements.less
templates/sheets/global/partials/inventory-fieldset-items.hbs
templates/sheets/global/partials/inventory-item.hbs

Added buttons to features on characters, and actions on adversary/environment
- Closes #195 

195 - Action Buttons

---

lang/en.json
module/config/actorConfig.mjs
module/data/item/armor.mjs
module/data/item/weapon.mjs
module/documents/tooltipManager.mjs
module/helpers/handlebarsHelper.mjs
module/systemRegistration/handlebars.mjs
styles/daggerheart.less
styles/less/ux/index.less
styles/less/ux/tooltip/tooltip.less
templates/sheets/global/tabs/tab-actions.hbs
templates/sheets/global/tabs/tab-features.hbs
templates/sheets/items/feature/header.hbs
templates/ui/tooltip/action.hbs
templates/ui/tooltip/adversary.hbs
templates/ui/tooltip/armor.hbs
templates/ui/tooltip/beastform.hbs
templates/ui/tooltip/consumable.hbs
templates/ui/tooltip/domainCard.hbs
templates/ui/tooltip/feature.hbs
templates/ui/tooltip/miscellaneous.hbs
templates/ui/tooltip/parts/tooltipTags.hbs
templates/ui/tooltip/weapon.hbs

Added templates for all 'advanced' tooltips.
- Closes #199
**Domain Card**
**Weapon**
**Armor**
**Consumables**
**Misc**
**Feature**
**Adversary**
**Attack**
It's possible the tooltips may get repetative in places, since we for instance render both the Domain card description - aswell as the actions of the Domain card with their descriptions, and there's probably a fair bit of overlap in their texts.

199 - Tooltips

---

styles/less/sheets/actors/adversary/sheet.less
styles/less/sheets/actors/adversary/sidebar.less
styles/less/sheets/actors/character/sheet.less
styles/less/sheets/actors/character/sidebar.less
styles/less/sheets/actors/companion/header.less

- Fix firefox having troubles with style
- Closes #327 
---

fix firefox problems

---

lang/en.json
module/applications/sheets/actors/character.mjs
styles/less/sheets/actors/character/sidebar.less
templates/sheets/actors/character/sidebar.hbs

adds the ability for the armor slots to be edited via the character sheet
- Closes #337 
---

Iss337 - Allow armor slots to be edited from the character sheet

---

styles/less/sheets/actors/adversary/sidebar.less
styles/less/sheets/actors/character/sidebar.less
styles/less/sheets/actors/companion/header.less
styles/less/sheets/actors/environment/header.less

Removed all instances of justify-items and replaced with flex solution.
Firefox doesn't handle justify-items correctly.

[Fix] Remove justify-items

---

module/applications/hud/_module.mjs
rollup.config.mjs
styles/daggerheart.less

Extracting tagify css to build/tagify.css for safe use

[Fix] Tagify CSS

---

styles/less/ui/combat-sidebar/token-actions.less
templates/ui/combatTracker/combatTrackerSection.hbs

Closes #354 
Changed so that players can see each others actionTokens but can't interact with others tokens.

354 - ActionToken Visibility

---

module/applications/dialogs/resourceDiceDialog.mjs
module/data/actor/character.mjs
module/data/item/base.mjs
templates/dialogs/dice-roll/resourceDice.hbs
templates/sheets/global/partials/item-resource.hbs
templates/sheets/global/partials/resource-section.hbs

Based on this:
Fixed everything, except I'm not sure about the simple resource focus loss. Couldn't reproduce that.

[Fix] Resource Improvements

---

README.md

A very tiny tweak to the README to fix a broken link.
I don't think these two apply to a documentation-only PR:
---

Fix link to Developer Setup section in README

---

module/applications/ui/chatLog.mjs

Fix Damage chat message

---

styles/less/global/inventory-item.less

Fix item desc animation

---

daggerheart.mjs
lang/en.json
module/documents/chatMessage.mjs
module/enrichers/DualityRollEnricher.mjs
styles/less/dialog/dice-roll/roll-selection.less
templates/dialogs/dice-roll/rollSelection.hbs
templates/ui/chat/duality-roll.hbs

Adding RollDifficulty support in RollDialog/ChatMessage aswell as [[/dr]] and /dr.

[Feature] Roll Difficulty Support

---

.github/workflows/deploy.yml
src/packs/LICENSE

Added DPCGL License under src/packs. Made sure it's packaged along with system releases under packs/.
**EDIT**
Verified that it's added along in the release deploy by making a test version.

License Update

---

templates/dialogs/ownershipSelection.hbs

[Fixes] typo on a translation for ownershipSelection

---

styles/less/sheets/actors/character/effects.less
styles/less/sheets/actors/character/features.less
styles/less/sheets/actors/character/inventory.less
styles/less/sheets/actors/character/loadout.less
styles/less/sheets/actors/character/sheet.less
styles/less/sheets/actors/character/sidebar.less
styles/less/sheets/index.less
styles/less/utils/mixin.less
templates/sheets/actors/character/effects.hbs
templates/sheets/actors/character/sidebar.hbs
templates/sheets/global/partials/inventory-item-V2.hbs

- Fix scrollbar from tabs not fiting the available space in char sheet
- Add scrollbar into sidebar chat sheet once he has many items equippeds there, when hove the sidebar, the scrollbar will appear
- Add new mixings to handle sidebar styles
---

[BUGFIX] - Fix scroll problems in char sheet

---

lang/en.json
module/applications/ui/chatLog.mjs
module/dice/d20Roll.mjs
module/dice/dhRoll.mjs
module/dice/dualityRoll.mjs
styles/less/ui/chat/chat.less
templates/ui/chat/adversary-roll.hbs
templates/ui/chat/duality-roll.hbs

Handled these two parts of the task, so it shouldn't be closed, as there is still more:
- When using hope/fear automation --> Handle change in resources.
- Add some marker or notification that a reroll happened.

[Fix] 397 - Reroll Improvements

---

module/data/action/healingAction.mjs

Fix Healing Action target

---

lang/en.json
module/applications/sheets/actors/character.mjs
module/applications/sheets/api/application-mixin.mjs
module/data/actor/character.mjs
module/data/settings/Homebrew.mjs
templates/settings/homebrew-settings.hbs

Max Cards loadout switch & Homebrew setting

---

system.json

changes compendium type to Actor for adversaries and environments
---

fixed compendium setup for adversaries and environments

---

module/config/generalConfig.mjs
module/data/actor/adversary.mjs
module/data/actor/character.mjs
module/data/actor/companion.mjs
module/data/fields/actionField.mjs
module/dice/d20Roll.mjs
module/dice/damageRoll.mjs
module/dice/dhRoll.mjs
module/dice/dualityRoll.mjs

Fix async/await roll postEvaluate

---

system.json

loot compendium is in the wrong location, sorry 
---

forgot some misc to loot change stuff :O

---

daggerheart.mjs
module/applications/dialogs/d20RollDialog.mjs
module/enrichers/DualityRollEnricher.mjs
module/helpers/utils.mjs

1 - Allow getCommandTarget to return null when a flag is specified
2 - Adjust dr roll and dr roll enricher to have default values when nothing is selected
- Fixes #422 

Fix duality roll

---

lang/en.json
module/applications/dialogs/deathMove.mjs
module/config/generalConfig.mjs
module/documents/tooltipManager.mjs
styles/less/dialog/actions/action-list.less
styles/less/dialog/death-move/death-move-container.less
styles/less/dialog/downtime/downtime-container.less
styles/less/dialog/index.less
styles/less/utils/colors.less
templates/dialogs/deathMove.hbs
templates/ui/tooltip/death-move.hbs

- Apply style for death roll dialog
---

[Feature] Enhance death roll dialog style

---

module/data/actor/character.mjs

Fixed so that extra selected proficiciency is added correctly. It was being set, rather than added 😆

[BUG] Levelup Proficiency Fix

---

module/dice/dhRoll.mjs

Fix: make damage application works with automation settings on

---

daggerheart.mjs
module/helpers/utils.mjs
templates/sheets/global/partials/inventory-item-V2.hbs
templates/sheets/global/partials/item-resource.hbs

Fixed DiceValues placement in InventoryItemV2. Fixed parsing of ITEM.@ paths

[Fix] Fixed Resources

---

styles/less/global/index.less
styles/less/global/prose-mirror.less
styles/less/global/tab-description.less

- Add basic style to enrich editor aka `prose mirror`
- Closes #483 
---

[Bugfix] Fix style rules to enrich editor

---

styles/less/global/item-header.less
styles/less/utils/colors.less
templates/sheets/items/domainCard/header.hbs

- Add domain icons into domain card header
- Closes #486 
---

[Feature] Add domain icon into domain cards

---

src/packs/communities/community_Highborne_DVw2mOCHB8i0XeBz.json
src/packs/communities/community_Loreborne_YsvlyqYoi8QQ8kwm.json
src/packs/communities/community_Orderborne_TY2TejenASXtS484.json
src/packs/communities/community_Ridgeborne_WHLA4qrdszXQHOuo.json
src/packs/communities/community_Seaborne_o5AA5J05N7EvH1rN.json
src/packs/communities/community_Slyborne_rGwCPMqZtky7SE6d.json
src/packs/communities/community_Underborne_eX0I1ZNMyD3nfaL1.json
src/packs/communities/community_Wanderborne_82mDY2EIBfLkNwQj.json
src/packs/communities/community_Wildborne_CRJ5pzJj4FjCtIlx.json
src/packs/communities/feature_Dedicated_7aXWdH3gzaYREK0X.json
src/packs/communities/feature_Know_the_Tide_07x6Qe6qMzDw2xN4.json
src/packs/communities/feature_Lightfoot_TQ1AIQjndC4mYmmU.json
src/packs/communities/feature_Low_Light_Living_aMla3xQuCHEwORGD.json
src/packs/communities/feature_Nomadic_Pack_2RSrQouA2zEJ5Xee.json
src/packs/communities/feature_Privilege_C7NR6qRatawZusmg.json
src/packs/communities/feature_Scoundrel_ZmEuBdL0JrvuA8le.json
src/packs/communities/feature_Steady_DYmmr5CknLtHnwuj.json
src/packs/communities/feature_Well_Read_JBZJmywisJg5X3tH.json

Add communities and community features

---

daggerheart.mjs

[Fix] /dr command

---

module/applications/sheets/api/application-mixin.mjs
module/data/item/subclass.mjs

- Fixed error where ActiveEffects created on an Item inside a Character were being created on the Character instead.
- Fixed error where characterCreation was failing subclass because of trying to use a value that didn't exist yet.

[Bug] Items And Features

---

module/data/actor/character.mjs
module/data/fields/action/rollField.mjs

Fixed so that spellcast attacks use the modifier instead of error:ing 🙃

[Fix] Spellcast Rolls

---

styles/less/global/elements.less
styles/less/global/inventory-item.less
styles/less/global/prose-mirror.less
styles/less/sheets/actors/adversary/sidebar.less
styles/less/sheets/actors/character/header.less

- Fix element styles in descriptions from `inventory-item-V2.hbs`

[Bugfix] Fix elements style from features descriptions

---

src/packs/adversaries/adversary_Adult_Flickerfly_G7jiltRjgvVhZewm.json
src/packs/adversaries/adversary_Demon_of_Avarice_pnyjIGxxvurcWmTv.json
src/packs/adversaries/adversary_Demon_of_Despair_kE4dfhqmIQpNd44e.json
src/packs/adversaries/adversary_Demon_of_Hubris_2VN3BftageoTTIzu.json
src/packs/adversaries/adversary_Demon_of_Jealousy_SxSOkM4bcVOFyjbo.json
src/packs/adversaries/adversary_Demon_of_Wrath_5lphJAgzoqZI3VoG.json
src/packs/adversaries/adversary_Dire_Bat_tBWHW00epmMnkawe.json
src/packs/adversaries/adversary_Dryad_wR7cFKrHvRzbzhBT.json
src/packs/adversaries/adversary_Elemental_Spark_P7h54ZePFPHpYwvB.json
src/packs/adversaries/adversary_Greater_Earth_Elemental_dsfB3YhoL5SudvS2.json
src/packs/adversaries/adversary_Greater_Water_Elemental_xIICT6tEdnA7dKDV.json
src/packs/adversaries/adversary_Head_Vampire_i2UNbRvgyoSs07M6.json
src/packs/adversaries/adversary_Huge_Green_Ooze_6hbqmxDXFOzZJDk4.json
src/packs/adversaries/adversary_Hydra_MI126iMOOobQ1Obn.json
src/packs/adversaries/adversary_Monarch_yx0vK2yfNVZKWUUi.json
src/packs/adversaries/adversary_Stag_Knight_KGVwnLq85ywP9xvB.json
src/packs/adversaries/adversary_Treant_Sapling_o63nS0k3wHu6EgKP.json
src/packs/adversaries/adversary_Vampire_WWyUp6Mxl1S3KYUG.json
src/packs/adversaries/adversary_Vault_Guardian_Gaoler_JqYraOqNmmhHk4Yy.json
src/packs/adversaries/adversary_Vault_Guardian_Sentinel_FVgYb28fhxlVcGwA.json
src/packs/adversaries/adversary_Vault_Guardian_Turret_c5hGdvY5UnSjlHws.json
src/packs/adversaries/adversary_Young_Ice_Dragon_UGPiPLJsPvMTSKEF.json

Closes #516
Added all Tier 3 Adversaries

[Feature] 496 - Adversaries Tier 3

---

src/packs/adversaries/adversary_Arch_Necromancer_WPEOIGfclNJxWb87.json
src/packs/adversaries/adversary_Fallen_Shock_Troop_OsLG2BjaEdTZUJU9.json
src/packs/adversaries/adversary_Fallen_Sorcerer_PELRry1vqjBzSAlr.json
src/packs/adversaries/adversary_Fallen_Warlord__Realm_Breaker_hxZ0sgoFJubh5aj6.json
src/packs/adversaries/adversary_Fallen_Warlord__Undefeated_Champion_RXkZTwBRi4dJ3JE5.json
src/packs/adversaries/adversary_Hallowed_Archer_kabueAo6BALApWqp.json
src/packs/adversaries/adversary_Hallowed_Soldier_VENwg7xEFcYObjmT.json
src/packs/adversaries/adversary_High_Seraph_r1mbfSSwKWdcFdAU.json
src/packs/adversaries/adversary_Kraken_4nqv3ZwJGjnmic8j.json
src/packs/adversaries/adversary_Oracle_of_Doom_befIqd5IYKg6eUz2.json
src/packs/adversaries/adversary_Outer_Realms_Abomination_A0SeeDzwjvqOsyof.json
src/packs/adversaries/adversary_Outer_Realms_Corrupter_ms6nuOl3NFkhPj1k.json
src/packs/adversaries/adversary_Outer_Realms_Thrall_moJhHgKqTKPS2WYS.json
src/packs/adversaries/adversary_Perfected_Zombie_CP6iRfHdyFWniTHY.json
src/packs/adversaries/adversary_Volcanic_Dragon__Ashen_Tyrant_pMuXGCSOQaxpi5tb.json
src/packs/adversaries/adversary_Volcanic_Dragon__Molten_Scourge_eArAPuB38CNR0ZIM.json
src/packs/adversaries/adversary_Volcanic_Dragon__Obsidian_Predator_ladm7wykhZczYzrQ.json
src/packs/adversaries/adversary_Zombie_Legion_YhJrP7rTBiRdX5Fp.json

Closes #497 
Added Tier 4 Adversaries

[Feature] 497 - Adversaries Tier 4

---

templates/ui/chat/parts/damage-part.hbs

Fix healing chat label

---

module/applications/sheets/api/application-mixin.mjs
module/applications/ui/chatLog.mjs
module/documents/item.mjs
templates/sheets/actors/adversary/features.hbs
templates/sheets/global/partials/inventory-fieldset-items-V2.hbs
templates/sheets/global/partials/inventory-item-V2.hbs
templates/ui/chat/ability-use.hbs

- Fixed so Adversary features can be sent to chat. 
- Fixed so ability-card.hbs works again

[Fix] Adversary Features To Chat

---

daggerheart.mjs
lang/en.json
module/applications/settings/appearanceSettings.mjs
module/applications/sheets/actors/character.mjs
module/applications/sheets/items/class.mjs
module/config/settingsConfig.mjs
module/data/actor/character.mjs
module/data/item/class.mjs
module/data/settings/Appearance.mjs
module/data/settings/Homebrew.mjs
module/documents/actor.mjs
module/helpers/utils.mjs
styles/less/ui/settings/settings.less
templates/settings/homebrew-settings.hbs

- Loadout can be unlimited
- # Domains in a class can be homebrewed.

[Feature] Loadout&Domains Homebrew

---

module/data/action/baseAction.mjs
module/documents/activeEffect.mjs
module/documents/chatMessage.mjs

ActiveEffect values can now specify ORIGIN. to grab the value from the origin

[Feature] ActiveEffects origins

---

daggerheart.mjs
module/dice/_module.mjs
module/dice/dualityDie.mjs
module/dice/dualityRoll.mjs

- Closes https://github.com/Foundryborne/daggerheart/issues/511
---

Remove DualityDie class

---

module/applications/ui/chatLog.mjs
styles/less/ui/chat/chat.less
templates/ui/chat/parts/roll-part.hbs

Added back reroll of Hope&Fear dice. Other dice are more complicated 🙃

[Fix] Hope&Fear reroll

---

daggerheart.mjs
module/config/flagsConfig.mjs
module/config/generalConfig.mjs
src/packs/journals/journal_Welcome___Information_g7NhKvwltwafmMyR.json
system.json

-Added Journal Compendium
- Added welcome message that shows up first time. Info will be expanded on.

[Feature] Journal Compendium

---

module/data/chat-message/adversaryRoll.mjs
module/dice/d20Roll.mjs
module/documents/actor.mjs
styles/less/sheets/actors/adversary/actions.less
styles/less/sheets/actors/adversary/sheet.less
styles/less/sheets/actors/adversary/sidebar.less
styles/less/sheets/actors/character/sheet.less
styles/less/sheets/actors/character/sidebar.less
styles/less/ui/chat/chat.less
templates/sheets/actors/adversary/sidebar.hbs
templates/ui/chat/parts/damage-part.hbs
templates/ui/chat/parts/roll-part.hbs

- Fix Character Sheet sidebar scroll
- Fix Adversary Sheet main & sidebar scroll
- Fix `+` sign in Roll Chat message
- Prevent user without OBSERVER permissions on Chat Message actor owner to see difficulty in Roll Chat message
---

Small Fixes

---

module/data/fields/action/rollField.mjs

The check was too optimistic and didn't respect undefined path.

[Fix] DiceSet Roll

---

src/packs/domains/domainCard_A_Soldier_s_Bond_Y08dLFuPXsgeRrHi.json
src/packs/domains/domainCard_Battle_Cry_Ef1JsUG50LIoKx2F.json
src/packs/domains/domainCard_Battle_Hardened_NeEOghgfyDUBTwBG.json
src/packs/domains/domainCard_Battle_Monster_P0ezScyQ5t8ruByf.json
src/packs/domains/domainCard_Blade_Touched_Gb5bqpFSBiuBxUix.json
src/packs/domains/domainCard_Champion_s_Edge_rnejRbUQsNGX1GMC.json
src/packs/domains/domainCard_Deadly_Focus_xxZOXC4tiZQ6kg1e.json
src/packs/domains/domainCard_Fortified_Armor_oVa49lI107eZILZr.json
src/packs/domains/domainCard_Frenzy_MMl7abdGRLl7TJLO.json
src/packs/domains/domainCard_Get_Back_Up_BFWN2cObMdlk9uVz.json
src/packs/domains/domainCard_Glancing_Blow_nCNCqSH7UgW4O3To.json
src/packs/domains/domainCard_Gore_and_Glory_3zvjgZ5Od343wHzx.json
src/packs/domains/domainCard_Not_Good_Enough_xheQZOIYp0ERQhT9.json
src/packs/domains/domainCard_Onslaught_I7pNsQ9Yx6mRJX4V.json
src/packs/domains/domainCard_Rage_Up_GRL0cvs96vrTDckZ.json
src/packs/domains/domainCard_Reaper_s_Strike_MCgNRlh0s5XUPCfl.json
src/packs/domains/domainCard_Reckless_2ooUo2yoilGifY81.json
src/packs/domains/domainCard_Scramble_5bBU9jWHOuOY12lR.json
src/packs/domains/domainCard_Versatile_Fighter_wQ53ImDswEHv5SGQ.json
src/packs/domains/domainCard_Vitality_sWUlSPOJEaXyQLCj.json
src/packs/domains/domainCard_Whirlwind_anO0arioUy7I5zBg.json

initial commit of blade domain cards & actions
- Closes #469 
---

added Blade Domain Cards

---

styles/less/global/elements.less
templates/dialogs/dice-roll/costSelection.hbs

Fix css cost

---

src/packs/domains/domainCard_Bone_Touched_ON5bvnoQBy0SYc9Y.json
src/packs/domains/domainCard_Boost_VKAHS6eWz28ukcDs.json
src/packs/domains/domainCard_Brace_QXs4vssSqNGQu5b8.json
src/packs/domains/domainCard_Breaking_Blow_8UANBgSdhMZ0sqfO.json
src/packs/domains/domainCard_Cruel_Precision_bap1eCWryPNowbyo.json
src/packs/domains/domainCard_Deathrun_xFOSn8IVVNizgHFq.json
src/packs/domains/domainCard_Deft_Maneuvers_dc4rAXlv95srZUct.json
src/packs/domains/domainCard_Ferocity_jSQsSP61CX4MhSN7.json
src/packs/domains/domainCard_I_See_It_Coming_Kp6RejHGimnuoBom.json
src/packs/domains/domainCard_Know_Thy_Enemy_O38MQMhJWdZnXi6b.json
src/packs/domains/domainCard_On_the_Brink_zbxPl81kbWEegKQN.json
src/packs/domains/domainCard_Rapid_Riposte_tceJDcCUefrMS2Ov.json
src/packs/domains/domainCard_Recovery_gsiQFT6q3WOgqerJ.json
src/packs/domains/domainCard_Redirect_faU0XkJCbar69PiN.json
src/packs/domains/domainCard_Signature_Move_LWRkhNY968Cu2Zl5.json
src/packs/domains/domainCard_Splintering_Strike_TYKfM3H9vBXyWiH4.json
src/packs/domains/domainCard_Strategic_Approach_5b1awkgTmMp3FVrm.json
src/packs/domains/domainCard_Swift_Step_H6TqCJBaa1eWEQ1z.json
src/packs/domains/domainCard_Tactician_WChWEH36lUpXAC0K.json
src/packs/domains/domainCard_Untouchable_9QElncQUDSakuSdR.json
src/packs/domains/domainCard_Wrangle_9DwSxHoUwl8Kxj3n.json

Closes #470 
Initial versions of bone domain cards. A lot of them didn't get much implementation because there's a lot of aweful designs in these cards.

[Feature] 470 - Bone Domain Compendium

---

module/data/actor/adversary.mjs
module/data/actor/character.mjs
module/data/actor/companion.mjs
module/data/fields/actorField.mjs

Closes #556 
Added so characters start with 2 hope

[Bug] 556 - Character Initial Hope

---

src/packs/classes/class_Wizard_5LwX4m8ziY3F1ZGC.json
src/packs/classes/feature_Not_This_Time_h3VE0jhcM5xHKBs4.json
src/packs/classes/feature_Prestidigitation_SG2uw8h5YuwDviCn.json
src/packs/classes/feature_Strange_Patterns_6YsfFjmCGuFYVhT4.json
src/packs/classes/folders_Wizard_SwEjiVLbnXT2x9Lz.json
src/packs/classes/folders_Wizard_utPGR3Z1uORKlNQw.json
src/packs/classes/loot_Tiny_Elemental_Pet_UUp0YGFj7E4x7Z6Z.json
src/packs/classes/loot_Untranslated_Book_fhg3NK99tcgYQxdY.json
src/packs/subclasses/feature_Accomplished_0wCctRupJAv5hTuE.json
src/packs/subclasses/feature_Adept_v511C6GMShsBblah.json
src/packs/subclasses/feature_Battlemage_Y9eGMewnFZgPvX0M.json
src/packs/subclasses/feature_Brilliant_2A0HBDxGc4gEARou.json
src/packs/subclasses/feature_Conjure_Shield_oirsCnN66GOlK3Fa.json
src/packs/subclasses/feature_Face_Your_Fear_D3ffFWSXCza4WGcM.json
src/packs/subclasses/feature_Fueled_by_Fear_hNqLf3zEfKRzSbvq.json
src/packs/subclasses/feature_Have_No_Fear_8TH6h6a36h09mf6d.json
src/packs/subclasses/feature_Honed_Expertise_w1BwNKxbQOSizLmZ.json
src/packs/subclasses/feature_Perfect_Recall_HzPa5U0EQhDfFTqW.json
src/packs/subclasses/feature_Prepared_YS52ZGdce605wNVT.json
src/packs/subclasses/feature_Thrive_in_Chaos_1nmFmkNXY6OYyyju.json
src/packs/subclasses/folders_Wizard_8dyHGlppj08jYLIO.json
src/packs/subclasses/folders_Wizard_Bb9SLVpYHGBrOB59.json
src/packs/subclasses/folders_Wizard_IIW7boHWq1QoYwOQ.json
src/packs/subclasses/folders_Wizard_t8AkyVM60h7WuLOD.json
src/packs/subclasses/subclass_School_Of_Knowledge_qqQlgCqhOivUFoQn.json
src/packs/subclasses/subclass_School_Of_War_4y9Ph7RsCIAbkwTk.json

[Feature] 568 - Wizard

---

src/packs/domains/domainCard_Bolt_Beacon_BNevJyGk7hmN7XOY.json
src/packs/domains/domainCard_Divination_K8oFepK24UVsAX8B.json
src/packs/domains/domainCard_Final_Words_Nbw6Jnh1vRZzwHQI.json
src/packs/domains/domainCard_Healing_Hands_WTlhnQMajc1r8i50.json
src/packs/domains/domainCard_Healing_Strike_XtSc0jIJLOoMTMYS.json
src/packs/domains/domainCard_Invigoration_X8OfkEoI5gLTRf1B.json
src/packs/domains/domainCard_Life_Ward_OszbCj0jTqq2ADx9.json
src/packs/domains/domainCard_Mending_Touch_TGjR4vJVNbQRV8zr.json
src/packs/domains/domainCard_Overwhelming_Aura_iEBLySZD9z8CLdz7.json
src/packs/domains/domainCard_Reassurance_iYNVTB7uAD1FTCZu.json
src/packs/domains/domainCard_Restoration_wUQFsRtww18naYaq.json
src/packs/domains/domainCard_Resurrection_z30ciOwQI7g3tHla.json
src/packs/domains/domainCard_Salvation_Beam_4uAFGp3LxiC07woC.json
src/packs/domains/domainCard_Second_Wind_ffPbSEvLuFrFsMxl.json
src/packs/domains/domainCard_Shape_Material_db4xV3YErHRslbVE.json
src/packs/domains/domainCard_Shield_Aura_rfIv6lln40Fh6EIl.json
src/packs/domains/domainCard_Smite_U1uWJE94HZVudujz.json
src/packs/domains/domainCard_Splendor_Touched_JT5dM3gVL6chDBYU.json
src/packs/domains/domainCard_Stunning_Sunlight_lRHo6ZkK1zybeEoG.json
src/packs/domains/domainCard_Voice_of_Reason_t3RRGH6mMYYJJCcF.json
src/packs/domains/domainCard_Zone_of_Protection_lOZaRb4fCVgQsWB5.json

Setup splendor cards

---

src/packs/journals/journal_Welcome___Information_g7NhKvwltwafmMyR.json

added a small note about missing automations to the welcome journal
---

updated journal with note about automations

---

daggerheart.mjs
module/documents/_module.mjs
module/documents/templateManager.mjs
module/enrichers/TemplateEnricher.mjs

Added a TemplateManager singleton for creating movable previewTemplates. This greatly improves the usability of enriched template placement buttons.

[Feature] Template Manager

---

lang/en.json
module/config/actorConfig.mjs
module/data/actor/base.mjs
module/data/item/base.mjs
module/data/settings/Automation.mjs
module/helpers/utils.mjs
templates/settings/automation-settings.hbs

Added a Setting that controls if scroll texts should be shown on resource change

[Feature] Scroll Texts

---

lang/en.json
module/applications/dialogs/downtime.mjs
module/config/itemConfig.mjs
module/data/item/base.mjs
styles/less/dialog/downtime/downtime-container.less
templates/dialogs/downtime/downtime.hbs
templates/sheets/global/partials/resource-section.hbs

- Downtime window now enumerates the actions/resources that will be refreshed upon completion. 
- Resources can now specify their progression direction

[Feature] Downtime Refresh Resources

---

module/applications/levelup/levelup.mjs
styles/less/dialog/index.less
styles/less/dialog/level-up/footer.less
styles/less/dialog/level-up/navigation-container.less
styles/less/dialog/level-up/selections-container.less
styles/less/dialog/level-up/sheet.less
styles/less/dialog/level-up/summary-container.less
styles/less/dialog/level-up/tiers-container.less
styles/less/global/elements.less
templates/components/card-preview.hbs
templates/levelup/tabs/footer.hbs
templates/levelup/tabs/selections.hbs
templates/levelup/tabs/summary.hbs
templates/levelup/tabs/tab-navigation.hbs

- Style Level Up application
- Closes #611 
---

[Feature] Style level up application

---

src/packs/domains/domainCard_Rage_Up_GRL0cvs96vrTDckZ.json

This is only the fix to the effect and cost that was incorrectly setup on rage-up. There is still the issue of the two effects weirdly being mutually exclusive.

Fix the effect of rage up - Compendium only

---

lang/en.json
module/applications/dialogs/multiclassChoiceDialog.mjs
module/applications/levelup/characterLevelup.mjs
module/applications/levelup/levelup.mjs
module/applications/settings/homebrewSettings.mjs
module/applications/sheets/items/class.mjs
module/applications/sheets/items/domainCard.mjs
module/applications/ux/filter-menu.mjs
module/config/domainConfig.mjs
module/data/item/domainCard.mjs
module/data/settings/Homebrew.mjs
module/helpers/utils.mjs
styles/less/global/elements.less
styles/less/global/item-header.less
styles/less/ui/index.less
styles/less/ui/settings/homebrew-settings/domains.less
styles/less/ui/settings/settings.less
styles/less/utils/colors.less
templates/settings/homebrew-settings/domains.hbs
templates/settings/homebrew-settings/downtime.hbs
templates/settings/homebrew-settings/footer.hbs
templates/settings/homebrew-settings/settings.hbs
templates/sheets/items/domainCard/header.hbs
templates/sheets/items/domainCard/settings.hbs

- Added homebrew domains to Automation Settings
- Automation Settings now have tabs
- Fixed Tagify to properly distinguish between names and values. Previously it erroniously required name and value to be the same to work properly.

[Feature] Homebrew Domains

---

module/applications/characterCreation/characterCreation.mjs
module/applications/levelup/levelup.mjs
module/config/generalConfig.mjs
module/data/action/baseAction.mjs
module/documents/activeEffect.mjs
module/helpers/utils.mjs
styles/less/dialog/character-creation/selections-container.less
styles/less/dialog/level-up/selections-container.less
styles/less/dialog/level-up/tiers-container.less
templates/characterCreation/setupTabs/ancestry.hbs
templates/levelup/tabs/selections.hbs

Closes #647
Closes #654
- Fixed that DomainCards were losing their effects when coming from CharacterCreation
- Fixed some Levelup styling
- Fixed CharacterCreation Ancestry card styling

[Fix] 654 - CharacterCreation DomainCard Effects

---

templates/ui/tooltip/beastform.hbs

not sure why these partials were removed 
adding them back shows the extra info
- Fixes #679
- Closes #679
---

[fix] 679 - add beastform advantage and features to tooltip

---

module/applications/sheets/items/subclass.mjs

Issue #694 mentions that the subclass window isn't completely in width of window but is also not resizable. 
Making the window resizable seems a fine solution 
- Fixes #694
- Closes #694
---

make subclass window resizable

---

templates/dialogs/dice-roll/header.hbs

Changing the title so it's more clear you've switched to a reaction roll

[fix] SimpleReaction Roll Improvement

---

.github/workflows/deploy.yml
package.json
system.json
tools/pullYMLtoLDBBuild.mjs

[Fix] Deploy Script

---

templates/settings/variant-rules.hbs

- Remove Very Far Field
- Fixes #711 
---

[Bugfix] Eemove very far field from variant rules range section

---

module/applications/ui/itemBrowser.mjs
styles/less/ui/item-browser/item-browser.less

- Fix columns style from Class Items
- Fix Domains from class not haveing space after comma
- Fix Compedium position
- Fixes #714 
Part of the code in `itemBroser.mjs` was formated by prettier extension 
---

[Bugfix] Fix item list columns and pretier itemBrowser.mjs

---

README.md

updated readme file
DO NOT MERGE YET

updated readmy for release

---

module/data/action/baseAction.mjs

Closes #756 
Fixed so fear is available as a resource to be deducted by actions

[Bug] 756 - Action Fear Deduction

---

module/config/itemConfig.mjs
src/packs/items/weapons/weapon_Aantari_Bow_ijodu5yNBoMxpkHV.json
src/packs/items/weapons/weapon_Advanced_Arcane_Frame_Wheelchair_la3sAWgnvadc4NvP.json
src/packs/items/weapons/weapon_Advanced_Broadsword_WtQAGz0TUgz8Xg70.json
src/packs/items/weapons/weapon_Advanced_Small_Dagger_0thN0BpN05KT8Avx.json
src/packs/items/weapons/weapon_Arcane_Frame_Wheelchair_XRChepscgr75Uug7.json
src/packs/items/weapons/weapon_Broadsword_1cwWNt4sqlgA8gCT.json
src/packs/items/weapons/weapon_Improved_Arcane_Frame_Wheelchair_N9P695V5KKlJbAY5.json
src/packs/items/weapons/weapon_Improved_Broadsword_OcKeLJxvmdT81VBc.json
src/packs/items/weapons/weapon_Improved_Shortsword_rSyBNRwemBVuTo3H.json
src/packs/items/weapons/weapon_Improved_Small_Dagger_nMuF8ZDZ2aXZVTg6.json
src/packs/items/weapons/weapon_Keeper_s_Staff_q382JqMkqLaaFLIr.json
src/packs/items/weapons/weapon_Knuckle_Claws_SFqganS8Du4aEKjQ.json
src/packs/items/weapons/weapon_Legendary_Arcane_Frame_Wheelchair_gA2tiET9VHGhwMoO.json
src/packs/items/weapons/weapon_Legendary_Broadsword_y3hfTPfZhMognyaJ.json
src/packs/items/weapons/weapon_Legendary_Shortsword_dEumq3BIZBk5xYTk.json
src/packs/items/weapons/weapon_Legendary_Small_Dagger_Px3Rh3kIvAqyISxJ.json
src/packs/items/weapons/weapon_Primer_Shard_SxcblanBvqaest3A.json
src/packs/items/weapons/weapon_Shortsword_cjGZpXCoshEqi1FI.json
src/packs/items/weapons/weapon_Small_Dagger_wKklDxs5nkzILNp4.json
src/packs/items/weapons/weapon_Spiked_Shield_vzyzFwLUniWZV1rt.json
src/packs/items/weapons/weapon_Thistlebow_I1nDGpulg29GpWOW.json
src/packs/items/weapons/weapon_War_Scythe_z6yEdFYQJ5IzgTX3.json

Closes #763 
- Fixed Reliable active effect
- Improved Paired and  LockedOn active effects with rangeDependency
- Updated all instances of reliable in the Compendium so the changes take effect there.

[Fix] 763 - WeaponFeature Fixing

---

system.json

Basic details update to add author details and discord mapping for myself.

Add author details and name mapping for chrisryan10

---

src/packs/classes/feature_Sneak_Attack_5QqpEwmwkPfZHpMW.json

Corrected sneak attack active effect

[Fix] Sneak Attack

---

module/applications/sheets/api/application-mixin.mjs

Added translation on inventory descriptions

[Fix] Effect Descriptions

---

lang/en.json
module/config/generalConfig.mjs

Added missing scene refreshType

[Fix] Added missing scene refresh

---

module/applications/levelup/characterLevelup.mjs
module/applications/levelup/companionLevelup.mjs
module/data/actor/character.mjs
module/data/item/class.mjs
module/data/item/subclass.mjs
module/documents/actor.mjs
module/helpers/utils.mjs
templates/sheets/actors/character/header.hbs

- Fixed crash on experience selection. 
- Fixed subclass error on multiclassing
- Fixed so multiclasses do not gain the hope feature for the class
- Fixed so Class/Subclass features are properly deleted on delevel
- Removed automatic deletion of features on delevel when not using levelup auto
- Fixed so custom domains are available when multiclassing

[Fix] Levelup Fixes

---

module/applications/levelup/characterLevelup.mjs
module/applications/levelup/companionLevelup.mjs

Closes #831 
Levelup dialog was crashing on exp increase selection

[Fix] Fixed Levelup Exp Increase

---

templates/dialogs/dice-roll/rollSelection.hbs

The Fear label lacked a localization path
- [ X ] Code cleanup/refactor
- [ X ] Manual testing

Update localization of rollSelection.hbs

---

templates/ui/combatTracker/combatTrackerHeader.hbs

Closes #828 
Removed the unintended titlebar clutter.

[Fix] 828 - Encounter Titlebar Clutter

---

module/applications/dialogs/downtime.mjs
system.json

Closes #850 
Fixed the filtering of refreshable features

[Fix] 850 - Downtime Refreshes

---

module/applications/sheets/api/item-attachment-sheet.mjs
module/data/item/weapon.mjs

Hid item attachments tab for now until it's fixed and upgraded.

[Fix] Hide Item Attachments

---

lang/en.json
module/applications/levelup/companionLevelup.mjs
module/applications/sheets/actors/companion.mjs
module/data/actor/character.mjs
module/data/actor/companion.mjs
module/data/levelTier.mjs
module/data/levelup.mjs
module/documents/actor.mjs
styles/less/sheets/actors/companion/header.less
templates/sheets-settings/companion-settings/details.hbs
templates/sheets-settings/companion-settings/experiences.hbs
templates/sheets/actors/companion/details.hbs
templates/sheets/actors/companion/header.hbs

Fixes #862 
Fixes #742 
Changed so companion can level up on its own

[Feature] Companion Independent Levelup

---

module/canvas/placeables/token.mjs

Fixed a possible undefined case

[Fix] 897 Effect Drawing Error

---

lang/en.json
module/applications/sheets/api/application-mixin.mjs
module/data/item/domainCard.mjs
module/data/settings/Appearance.mjs
styles/less/global/inventory-item.less
system.json
templates/settings/appearance-settings.hbs
templates/sheets/global/partials/inventory-item-V2.hbs

- add new text lang to auto extend descriptions
- add auto extend method in `application-mixing.mjs`
- enhance hover for items
- add domain level into tags array
- add @moliloo info into `system.json`
- Closes #818
- Closes #833 
- Closes #605 
---

[Feature] Descriptions enhancements

---

templates/hud/tokenHUD.hbs

Fixes #910
Add missiing parts on the template

[BUG] - Movement Button selector not showing current mode

---

module/applications/dialogs/d20RollDialog.mjs

- Fixes https://github.com/Foundryborne/daggerheart/issues/886
---

Fix roll dialog default rollmode value

---

module/data/actor/character.mjs
module/data/item/class.mjs
module/data/item/feature.mjs
module/data/item/subclass.mjs

Fixes #940 
Changed Class/Multiclass to simple getters to avoid having to keep them up to date

[Fix] 940 Character Import

---

.github/ISSUE_TEMPLATE/typo_report.md

Add a typo template that can be used to quickly add small corrections to thing like compendium items or descriptions, or stats of items, etc

Add typo template

---

.github/PULL_REQUEST_TEMPLATE/community_pull_request_template.md
pull_request_template.md

[PR] testing something

---

module/data/action/baseAction.mjs
module/documents/chatMessage.mjs
system.json
templates/ui/tooltip/action.hbs

- There were references to the unreleased expandChatMessage setting in ChatMessage which caused rolls to fail.
- Fixed localization for Unarmed Attack.

[Fix] Fixed 1.0.6 Errors

---

module/dice/dhRoll.mjs

Fixes #1003 
Fixed so character dice rolls await the DiceSoNice animation before consuming resources

[Fix] 1003 - DiceSoNice Await Animation

---

module/documents/actor.mjs

---
name: Pull Request
about: Create a new pull request
title: "[PR] <Insert Title here>"
labels: pr
assignees: ''
---
Is this a community PR? Please go to preview tab and click [here](?expand=1&template=community_pull_request_template.md). If not, delete this line.
---

Fix double damageKeyToNumber

---

module/data/action/attackAction.mjs
module/data/actor/adversary.mjs

Closes #1070
The basic attack damage shown in the sidebar is modified if horde damage is active
https://github.com/user-attachments/assets/7797870b-5d91-4ca5-aa5e-de0246871556

[Feature] 1070 Horde Adversary Sidebar Damage

---

styles/less/global/chat.less

Improved text color on chat-message flavor texts.

[Fix] RollMessage FlavorText

---

module/data/item/subclass.mjs

Fixes #1040 
Fixed so subclasses can be dragged to the sheet when they're stored in a folder

[Fix] Subclass DragDrop

---

CONTRIBUTING.md

added note to translations

---

styles/less/ui/settings/homebrew-settings/domains.less

Simple fix for now. Setting a height and overflow.

[Fix] 1091 - Improve Homebrew Domain Container

---

module/applications/sheets/actors/character.mjs
module/config/flagsConfig.mjs

Closes #957 
Changed so the default domaincard view is list

[Fix] 957 - Default Loadout View

---

src/packs/adversaries/adversary_Oak_Treant_XK78QUfY8c8Go8Uv.json

Add motives and tactics for Oak Treant
- Closes #1155 

[PR] Add motives and tactics for Oak Treant

---

templates/dialogs/dice-roll/rollSelection.hbs

No issue raised. Noticed this typo in the button class.

Fixed typo in button class

---

lang/en.json
module/applications/sheets-configs/action-config.mjs
module/config/generalConfig.mjs
templates/actionTypes/cost.hbs
templates/actionTypes/range-target.hbs
templates/actionTypes/uses.hbs

Translation keys additions and fixes.
- Closes #952 
- [x ] Bug fix
- [x ] Manual testing

[PR] Add keys, update usage for translations

---

module/applications/sheets/actors/adversary.mjs
module/applications/sheets/actors/environment.mjs

Add support for Dice Values in Resources for Adversaries and Environments.
- Closes #1164 
If support for Dice Values and Resources were added to Companions, then this code could be moved to the DHBaseActorSheet (maybe it can anyway?).

Add dice value support to Advesaries and Environments

---

src/packs/beastforms/beastform_Powerful_Beast_m8BVTuJI1wCvzTcf.json

Fix the Powerful Beast transform for Errata changes.
- Closes #1178 

Update Powerful Beast for Errata changes

---

module/applications/sheets/api/application-mixin.mjs

This PR prevents item description expand animations from replaying between re-renders, and also fixes scroll position restoration between re-renders when expanded items are present.
Internally it moves the preservation of extend state to _preSyncPartState(), which occurs before the new element is mounted. It also adds the description enrichment to _renderHTML(), which also occurs before mounting but is an async function. Having the descriptions ready and expanded before mounting skips the animation entirely and allows scroll restoration to work.
- Closes #1173 
https://github.com/user-attachments/assets/f6841686-7f45-4fdc-8326-69a7c5dd6f24

[Community PR] Fix expanded item summary behavior when re-rendering
