- daggerheart.mjs
Removed non-existing template preload. Annoying error that was always showing up :grin:
> Bug - Unused Handlebar Preloads

- lang/en.json
- module/applications/levelup/levelup.mjs
- module/applications/sheets/actors/character.mjs
- module/data/levelData.mjs
- module/data/levelTier.mjs
- module/dice/dhRoll.mjs
- module/documents/actor.mjs
- Fixed so that features gained from companion levelup show up on the character sheet again.
- Changed so that these Feature items are actually embedded onto the character itself, rather than trying to use it from the companions item list. This is much more robust.
- The features list in the levelup data tracks if the levelup feature is in the partner's item list so it can be removed on delevel.
> Bugfix - Companion Levelup Features

- daggerheart.mjs
- lang/en.json
- module/applications/_module.mjs
- module/applications/hud/_module.mjs
- module/applications/hud/tokenHUD.mjs
- module/data/settings/Appearance.mjs
- styles/daggerheart.less
- styles/less/hud/index.less
- styles/less/hud/token-hud/token-hud.less
- templates/hud/tokenHUD.hbs
- templates/settings/appearance-settings.hbs
Added a separation of system effects and generic effects on token status effects. Can be turned off in settings.
- Closes #259
> 259 - Missing Status Effects

- module/data/actor/character.mjs
Evasion property setting in Character data had disappeared during reworks. Returned it.
- Closes #333
> [Bug] Evasion Not Shown On Character Sheet

- daggerheart.mjs
- lang/en.json
- module/config/generalConfig.mjs
- module/data/actor/character.mjs
- module/data/actor/companion.mjs
- module/dice/d20Roll.mjs
- module/dice/dhRoll.mjs
- Removed trait useage for companion attack. Uneeded and was causing errors
- Fixed so bonus hope is calculated on the Character and not on the Companion.
- Companions rolling with hope now give hope to the Character.
> [Bug] Companion Trait Useage

- daggerheart.mjs
- lang/en.json
- module/canvas/placeables/_module.mjs
- module/canvas/placeables/token.mjs
- module/data/action/damageAction.mjs
- module/data/actor/adversary.mjs
- module/data/actor/character.mjs
- module/data/item/class.mjs
- module/data/settings/Automation.mjs
- styles/less/dialog/dice-roll/roll-selection.less
- templates/actionTypes/damage.hbs
- templates/dialogs/dice-roll/rollSelection.hbs
- templates/settings/automation-settings.hbs
- templates/sheets-settings/adversary-settings/attack.hbs
- templates/sheets-settings/adversary-settings/details.hbs
- templates/sheets/actors/adversary/header.hbs
- templates/sheets/actors/adversary/sidebar.hbs
- templates/sheets/actors/environment/header.hbs
- templates/ui/tooltip/adversary.hbs
Little grab-bag of things I noticed while checking up on Adversary.
- Non-transferred, active ActiveEffects are now displayed on the canvas token.
- Added a setting for Horde Damage (lowered damage on half hit points or lower) to the Adversary attack.
- There's an automation setting for automatically applying this via active effect.
- Fixed light-mode color for D20 dice in roll dialog for adversaries.
- Bunch of localization fixes
> [Feature/Fixes] Adversary Touchups

- module/documents/tooltipManager.mjs
While working on https://github.com/Foundryborne/daggerheart/issues/374, I noticed that the tooltip describing downtime moves can obscure potentially useful information, like the number of remaining moves.
This PR moves the downtown dialog's move tooltip to the right so that the full downtime dialog remains visible.
Before, the tooltip hides potentially useful information:
After, the tooltip is off to the side:
---
> Move downtime move tooltip from top to right.

- lang/en.json
- module/applications/settings/homebrewSettings.mjs
- module/applications/sheets/items/beastform.mjs
- module/config/generalConfig.mjs
- module/data/actor/character.mjs
- module/data/fields/actionField.mjs
- module/data/item/weapon.mjs
- module/documents/activeEffect.mjs
- Reseting HomebrewSettings failed because of the changed Action structure. Fixed.
- The default rest actions had lost their SystemPath, so they failed to update. Restored them 
- Added a temp fix to a problem where you couldn't edit the healing section of an action in the config.
> [Bug] Downtime Actions Fixes

- module/applications/settings/appearanceSettings.mjs
- module/helpers/utils.mjs
The appearance change setting had the disadvatage tab read as advanated. Fixed the label to read disadvantage for that tab. 
When rolling duality dice with Dice so Nice not enabled, it would get an error. Now checks if the Dice So Nice module is enabled before attempting to apply custom colors. 
- Fixes #431
- Closes #431
---
> fix language display and attribute roll bug

- templates/sheets/global/partials/inventory-item-V2.hbs
Make drag and drop item works again by putting back data-item-id attributes for items.
- Fixes #407 
> Fix: make drag and drop item works again  (#407)

- module/applications/hud/tokenHUD.mjs
- module/applications/sheets-configs/activeEffectConfig.mjs
- module/canvas/placeables/token.mjs
- module/documents/activeEffect.mjs
- module/documents/actor.mjs
- templates/sheets/global/partials/inventory-item-V2.hbs
- Fixed so genericStatuses aren't shown in activeEffectConfig if the system setting is turned off. 
- Fixed localization of genericStatuses in Inventory-ItemV2, they weren't before.
- Effects with statuses on them will show them on the token - they will also be shown as active in the Token HUD.
> [Feature] ActiveEffect Improvements

- module/canvas/placeables/token.mjs
It crash if I have a status on a token and I refresh Foundry. It's because it calls a include() function on a Set.
> fix: statuses are Set not Array, change includes() to has() in placebles/token.mjs

- templates/dialogs/dice-roll/rollSelection.hbs
Fixed so CostSelection is always in the RollSelection. Previously it was excluded in "lite" messages.
> [Fix] CostSelection In Rollmessage

- src/packs/adversaries/adversary_Minor_Chaos_Elemental_sRn4bqerfARvhgSV.json
Added path to an appropriate icon to represent the Minor Chaos Elemental's attack, Warp Blast.
Used "icons/magic/light/beam-rays-magenta.webp" as the icon is appropriate and matches that used by Chaos Skull's Energy Blast attack.
- Closes #642 
Minimal change has been minimally tested - this is a cosmetic update only.
.<img width="406" height="134" alt="image" src="https://github.com/user-attachments/assets/a623d672-95bd-4221-a9a7-9b9a63f9721d" />
n/a
> [Fix] Add icon to Minor Chaos Elemental's Attack (Warp Blast)

- module/data/fields/action/beastformField.mjs
- module/data/item/beastform.mjs
- module/documents/tooltipManager.mjs
- styles/less/ux/tooltip/tooltip.less
- templates/actionTypes/beastform.hbs
- templates/sheets-settings/action-settings/effect.hbs
- templates/ui/tooltip/beastform.hbs
Improved tooltips with more data
> [Fix] 679 - Improved Beastform Tooltips

- templates/sheets/global/partials/domain-card-item.hbs
Fixes #594
The functioning of the div menu should be reviewed so that it is visible even when the mouse is not over the card-item element but has a context menu activated.
> [BUG] - domain card menu not working in loadout screen

- src/packs/ancestries/feature_Tusks_YhxD1ujZpftPu19w.json
> [FIX] Orc Ancestry character gets Tusk feature as "Base" in Inactive Effects

- module/data/item/armor.mjs
Closes #771 
The preUpdate was checking on `changes.system.armorFeatures` without respecting null which made it fail if any update was made without effecting system. Fixed.
> [Fix] 771 - Armor preUpdate

- module/data/activeEffect/beastformEffect.mjs
Fixed a spelling error that made the secondaryWeapon not be unequipped upon transforming.
> [Fix] Beastform Unequip SecondaryWeapon

- module/helpers/handlebarsHelper.mjs
Closes #791 
Fixed so the parseNumber handlebar helper can tolerate a missing actor.
> [Fix] 791 - Seaborne Parsing

- module/dice/damageRoll.mjs
- package.json
Alternate attempt at calculating max damage portion of critical roll.
- Fixes #889
- [ x] Bug fix
- [ x] Manual testing
When testing this, cover the following:
* different tier characters
* abilities that add to the damage, e.g. sneak attack
* check the modifiers are correct, e.g. weapon dam is 1d8 + 1, crit should appear as 1d8 + 1 + 8 (plus other bonuses).
> Change the critical damage max calculation

- module/systemRegistration/settings.mjs
Restricts the Variant Rules settings to the GM Only.
- Fixes #620
- [ x] Bug fix
- [ x] Manual testing
Tested as GM.
Tested as Player.
> Set the Variant Rules settings to GM Only

- module/applications/dialogs/damageReductionDialog.mjs
- module/data/fields/actorField.mjs
- module/helpers/utils.mjs
- src/packs/domains/domainCard_Get_Back_Up_BFWN2cObMdlk9uVz.json
- src/packs/domains/domainCard_Shrug_It_Off_JwfhtgmmuRxg4zhI.json
Fixes #924 
- Fixed damage reduction any not working
- Removed unneccessary `damageReduction.<>.enabled` flag. It's enough to just check if there is a cost available.
> [Fix] 924 - Damage Reduction Any

- module/applications/characterCreation/characterCreation.mjs
- module/applications/levelup/levelup.mjs
- system.json
Set the finish buttons on levelup and creation to disable after first click. Decided to do it this way rather than debounce because I don't trust how laggy user computers/servers will be.
> [Fix] Creation/Levelup disable finish button

- .env.example
- .gitignore
- README.md
- package.json
- tools/dev-setup.mjs
- tools/run-start.mjs
This PR introduces a configurable development environment setup that eliminates the need for developers to manually edit hardcoded paths in `package.json`. Instead of requiring each contributor to modify the repository files with their local Foundry installation paths, the system now uses environment variables with current values as fallbacks.
**Key improvements:**
- Developers can set up their environment with a single command: `npm run setup:dev -- --foundry-path="<path>" --data-path="<path>"`
- Environment variables are stored in a `.env` file (gitignored) for per-developer configuration
- Tested without `.env` file (fallback to original hardcoded paths)
- Tested with `.env` file (uses configured environment variables)
- Verified build processes (rollup, gulp) work correctly in both …
> [PR]Add setup script for development

- module/data/fields/foreignDocumentUUIDField.mjs
- module/helpers/utils.mjs
ForeignDocumentUUIDFields now accept document instances at update time.
The way of how selfCorrecting modifier is set is change so that it doesn't break IntelliSense in VScode.
- Fixes #389
> [PR][Feature] Improves ForeignDocumentUUIDArrayField for can use documents to update it.

- daggerheart.mjs
- lang/en.json
- module/applications/sheets/api/application-mixin.mjs
- module/applications/sheets/api/base-item.mjs
- module/config/settingsConfig.mjs
- module/data/actor/character.mjs
- module/data/item/base.mjs
- module/data/item/feature.mjs
- module/documents/actor.mjs
- module/helpers/utils.mjs
- module/systemRegistration/_module.mjs
- module/systemRegistration/migrations.mjs
- module/systemRegistration/settings.mjs
- system.json
Fix #1021 
Fix #1004 
- Changed so that features created on a Character are standalone compared to before. Holding all the info needed for functions.
Previously we relinked things, so that the Ancestry/Class etc on a character had the features on it pointing to the copied features existing in the Character Item Collection. This caused a lot of issues however,
Now all items with links on them on the Character simply keep their original links.
-------
I introduced one-time migrations based on a new `lastMigrationVersion` game setting. I couldn't come up with any other way to to be able to update the way I needed to.
> [Fix] ItemLink Fix

- module/documents/activeEffect.mjs
Closes #1058
The logic determining if subclass features should transfer to the character wasn't updated with the 1.1.0 model change. Fixed.
> [Fix] 1058 - Subclass Feature Transfer

- module/applications/sheets/actors/character.mjs
- system.json
Added the preset for the subclass Compendium Browser from character sheet.
> [Fix] Character Sheet Subclass Compendium Preset

- module/enrichers/DamageEnricher.mjs
- module/enrichers/DualityRollEnricher.mjs
- module/enrichers/TemplateEnricher.mjs
Closes #1086
Closes #1014  
- Fixed so enriched buttons are button type and don't trigger on enter click.
- Fixed so DamageEnriched button works properly again.
> [Fix] 1086 - Enrichment Buttons

- styles/less/ui/item-browser/item-browser.less
From #1103, I mentioned in the PR that the sort arrows were in the wrong direction. During a discord discussion I discovered that the sort arrows mean different things to different people. This change is an attempt to use icons that are less ambiguous for everyone.
There is no issue associated with this change (except the PR mentioned above). 
- [x ] Manual testing
Open the Compendium Browser and open Domain Cards (for example).  Sort the columns via the header bar. Note the different sort direction icons.
> Use less ambiguous sort direction symbols

- styles/less/global/elements.less
Replaces the global paragraph margin removal with removing the top margin of the first paragraph and the bottom margin of the last paragraph. This keeps the spacing between paragraphs and other elements unchanged.
It is still possible to make two (visual) paragraphs hug each other by pressing shift+enter, which inserts a breakline instead.
- Closes #1006
> [Community PR] Restore margins between paragraphs

- module/config/itemBrowserConfig.mjs
No issue created. I noticed a problem with the subclasses display in the character creation. Unfortunately in commit f1b6d3851dbed1559d88ecebc71d1bb537fd8b8b an error was made in merging? changes and we ended up with the subclass filter in the wrong location.
> [PR] Fix/filter error item browser config

- src/packs/adversaries/adversary_Fallen_Warlord__Undefeated_Champion_RXkZTwBRi4dJ3JE5.json
#960 added an unnecessary `chatDisplay` in the `bonuses` section of the Fallen Warlord: Undefeated Champion adversary. No other adversary has this. This removes it.
- Closes #1170 
> [PR] Remove Unnecessary Fallen Warlord chatDisplay

- styles/less/global/chat.less
Applies the object-position css property to the chat message avatar so that it is cropped similarly to the actor sheet.
- Fixes #1192 
Before
After
> [Community PR] Anchor chat message image crop to top
